name: 'Setup .NET with Cache'
description: 'Sets up .NET SDK with NuGet package caching for consistent builds'
author: 'Market Data Collector'

inputs:
  dotnet-version:
    description: '.NET SDK version to install'
    required: false
    default: '9.0.x'
  cache-suffix:
    description: 'Optional suffix for cache key to isolate caches between workflows'
    required: false
    default: ''

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.nuget-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5.1.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache NuGet packages
      id: nuget-cache
      uses: actions/cache@v5.0.3
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ inputs.cache-suffix }}${{ inputs.cache-suffix && '-' || '' }}${{ hashFiles('**/*.csproj', '**/*.fsproj', 'Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ inputs.cache-suffix }}${{ inputs.cache-suffix && '-' || '' }}
          ${{ runner.os }}-nuget-

    - name: Configure NuGet
      shell: bash
      run: |
        # Disable telemetry for faster operations
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=true" >> $GITHUB_ENV
        echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1" >> $GITHUB_ENV
