using System.Text;

namespace MarketDataCollector.Storage.Export;

/// <summary>
/// Generates loader and import scripts for various analysis tools.
/// Extracted from AnalysisExportService to isolate script generation concerns.
/// </summary>
internal sealed class ExportScriptGenerator
{
    /// <summary>
    /// Generates a loader script for the specified target tool.
    /// </summary>
    public async Task<string> GenerateLoaderScriptAsync(
        string outputDir,
        ExportProfile profile,
        List<ExportedFile> files,
        CancellationToken ct)
    {
        string scriptPath;
        string script;

        switch (profile.TargetTool.ToLowerInvariant())
        {
            case "python":
                scriptPath = Path.Combine(outputDir, "load_data.py");
                script = GeneratePythonLoader(files, profile);
                break;
            case "r":
                scriptPath = Path.Combine(outputDir, "load_data.R");
                script = GenerateRLoader(files, profile);
                break;
            case "postgresql":
                scriptPath = Path.Combine(outputDir, "load_data.sh");
                script = GeneratePostgresLoader(files, profile);
                break;
            default:
                return string.Empty;
        }

        await File.WriteAllTextAsync(scriptPath, script, ct);
        return scriptPath;
    }

    private string GeneratePythonLoader(List<ExportedFile> files, ExportProfile profile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine("Market Data Loader");
        sb.AppendLine($"Generated by MarketDataCollector - {profile.Name}");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine();
        sb.AppendLine("DATA_DIR = Path(__file__).parent");
        sb.AppendLine();

        if (profile.Format == ExportFormat.Parquet)
        {
            sb.AppendLine("""
def load_trades(symbol: str = None) -> pd.DataFrame:
    \"\"\"Load trade data into a pandas DataFrame.\"\"\"
    pattern = f"{symbol}_*.parquet" if symbol else "*.parquet"
    files = list(DATA_DIR.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No parquet files found matching {pattern}")
    return pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)


def load_quotes(symbol: str = None) -> pd.DataFrame:
    \"\"\"Load quote data into a pandas DataFrame.\"\"\"
    pattern = f"{symbol}_*.parquet" if symbol else "*quote*.parquet"
    files = list(DATA_DIR.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No quote files found matching {pattern}")
    return pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)

""");
        }
        else if (profile.Format == ExportFormat.Csv)
        {
            sb.AppendLine("""
def load_trades(symbol: str = None) -> pd.DataFrame:
    \"\"\"Load trade data into a pandas DataFrame.\"\"\"
    pattern = f"{symbol}_*.csv" if symbol else "*.csv"
    files = list(DATA_DIR.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No CSV files found matching {pattern}")
    return pd.concat([pd.read_csv(f, parse_dates=['Timestamp']) for f in files], ignore_index=True)

""");
        }

        sb.AppendLine("""
if __name__ == "__main__":
    # Example usage
    df = load_trades()
    print(f"Loaded {len(df):,} records")
    print(df.head())
""");

        return sb.ToString();
    }

    private string GenerateRLoader(List<ExportedFile> files, ExportProfile profile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Market Data Loader");
        sb.AppendLine($"# Generated by MarketDataCollector - {profile.Name}");
        sb.AppendLine();
        sb.AppendLine("library(tidyverse)");
        sb.AppendLine("library(lubridate)");
        sb.AppendLine();
        sb.AppendLine("data_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)");
        sb.AppendLine();
        sb.AppendLine("""
load_trades <- function(symbol = NULL) {
  pattern <- if (!is.null(symbol)) paste0(symbol, "_.*\\.csv$") else ".*\\.csv$"
  files <- list.files(data_dir, pattern = pattern, full.names = TRUE)

  if (length(files) == 0) {
    stop("No CSV files found")
  }

  df <- files %>%
    map_dfr(read_csv) %>%
    mutate(Timestamp = ymd_hms(Timestamp))

  return(df)
}

# Example usage
# trades <- load_trades("AAPL")
# head(trades)
""");

        return sb.ToString();
    }

    private string GeneratePostgresLoader(List<ExportedFile> files, ExportProfile profile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("# Market Data PostgreSQL Loader");
        sb.AppendLine($"# Generated by MarketDataCollector - {profile.Name}");
        sb.AppendLine();
        sb.AppendLine("DB_NAME=${1:-marketdata}");
        sb.AppendLine("DB_USER=${2:-postgres}");
        sb.AppendLine("SCRIPT_DIR=$(dirname \"$0\")");
        sb.AppendLine();
        sb.AppendLine("# Create tables");
        sb.AppendLine("psql -U $DB_USER -d $DB_NAME -f \"$SCRIPT_DIR/create_tables.sql\"");
        sb.AppendLine();
        sb.AppendLine("# Load data");

        foreach (var file in files.Where(f => f.Format == "csv"))
        {
            var tableName = $"market_{file.EventType?.ToLowerInvariant() ?? "data"}";
            sb.AppendLine($"psql -U $DB_USER -d $DB_NAME -c \"\\copy {tableName} FROM '$SCRIPT_DIR/{file.RelativePath}' WITH CSV HEADER\"");
        }

        sb.AppendLine();
        sb.AppendLine("echo \"Data loaded successfully\"");

        return sb.ToString();
    }
}
