using System.Text;

namespace MarketDataCollector.Storage.Packaging;

/// <summary>
/// Generates loader scripts, import scripts, and documentation files
/// for portable data packages across multiple languages and platforms.
/// </summary>
internal static class PackageScriptGenerator
{
    internal static string GenerateReadme(PackageManifest manifest, PackageOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {manifest.Name}");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(manifest.Description))
        {
            sb.AppendLine(manifest.Description);
            sb.AppendLine();
        }
        sb.AppendLine("## Package Information");
        sb.AppendLine();
        sb.AppendLine($"- **Package ID:** {manifest.PackageId}");
        sb.AppendLine($"- **Created:** {manifest.CreatedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"- **Creator Version:** {manifest.CreatorVersion}");
        sb.AppendLine($"- **Format:** {manifest.Format}");
        sb.AppendLine();
        sb.AppendLine("## Data Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Total Files:** {manifest.TotalFiles:N0}");
        sb.AppendLine($"- **Total Events:** {manifest.TotalEvents:N0}");
        sb.AppendLine($"- **Uncompressed Size:** {manifest.UncompressedSizeBytes:N0} bytes");
        sb.AppendLine($"- **Symbols:** {string.Join(", ", manifest.Symbols)}");
        sb.AppendLine($"- **Event Types:** {string.Join(", ", manifest.EventTypes)}");
        if (manifest.DateRange != null)
        {
            sb.AppendLine($"- **Date Range:** {manifest.DateRange.Start:yyyy-MM-dd} to {manifest.DateRange.End:yyyy-MM-dd}");
            sb.AppendLine($"- **Trading Days:** {manifest.DateRange.TradingDays}");
        }
        sb.AppendLine();
        sb.AppendLine("## Directory Structure");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine($"{manifest.Name}/");
        sb.AppendLine("├── manifest.json           # Package manifest with checksums");
        sb.AppendLine("├── README.md               # This file");
        sb.AppendLine("├── data/                   # Market data files");
        sb.AppendLine("├── metadata/               # Data dictionary and schemas");
        sb.AppendLine("└── scripts/                # Loader scripts for various tools");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Usage");
        sb.AppendLine();
        sb.AppendLine("### Python");
        sb.AppendLine("```python");
        sb.AppendLine("# See scripts/load_data.py for full example");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("df = pd.read_json('data/..../file.jsonl', lines=True)");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("### R");
        sb.AppendLine("```r");
        sb.AppendLine("# See scripts/load_data.R for full example");
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("df <- stream_in(file('data/..../file.jsonl'))");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Verification");
        sb.AppendLine();
        sb.AppendLine("All files include SHA256 checksums in `manifest.json` for integrity verification.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine($"*Generated by MarketDataCollector v{manifest.CreatorVersion}*");

        return sb.ToString();
    }

    internal static string GenerateDataDictionary(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Data Dictionary");
        sb.AppendLine();
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        if (manifest.Schemas != null)
        {
            foreach (var (eventType, schema) in manifest.Schemas)
            {
                sb.AppendLine($"## {eventType}");
                sb.AppendLine();
                sb.AppendLine("| Field | Type | Nullable | Description |");
                sb.AppendLine("|-------|------|----------|-------------|");

                foreach (var field in schema.Fields)
                {
                    sb.AppendLine($"| {field.Name} | {field.Type} | {(field.Nullable ? "Yes" : "No")} | {field.Description ?? ""} |");
                }

                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    internal static string GeneratePythonLoader(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Data Loader for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from typing import Optional, List");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_manifest() -> dict:");
        sb.AppendLine("    \"\"\"Load the package manifest.\"\"\"");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        return json.load(f)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_data(");
        sb.AppendLine("    symbol: Optional[str] = None,");
        sb.AppendLine("    event_type: Optional[str] = None,");
        sb.AppendLine("    date: Optional[str] = None");
        sb.AppendLine(") -> pd.DataFrame:");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("    Load market data into a pandas DataFrame.");
        sb.AppendLine("    ");
        sb.AppendLine("    Args:");
        sb.AppendLine("        symbol: Filter by symbol (e.g., 'AAPL')");
        sb.AppendLine("        event_type: Filter by event type (e.g., 'Trade', 'BboQuote')");
        sb.AppendLine("        date: Filter by date (e.g., '2024-01-15')");
        sb.AppendLine("    ");
        sb.AppendLine("    Returns:");
        sb.AppendLine("        DataFrame with matching data");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    dfs = []");
        sb.AppendLine("    ");
        sb.AppendLine("    for file_entry in manifest['files']:");
        sb.AppendLine("        # Apply filters");
        sb.AppendLine("        if symbol and file_entry.get('symbol', '').upper() != symbol.upper():");
        sb.AppendLine("            continue");
        sb.AppendLine("        if event_type and file_entry.get('eventType', '').lower() != event_type.lower():");
        sb.AppendLine("            continue");
        sb.AppendLine("        if date and file_entry.get('date', '')[:10] != date:");
        sb.AppendLine("            continue");
        sb.AppendLine("        ");
        sb.AppendLine("        file_path = PACKAGE_DIR / file_entry['path']");
        sb.AppendLine("        if file_path.exists():");
        sb.AppendLine("            df = pd.read_json(file_path, lines=True)");
        sb.AppendLine("            dfs.append(df)");
        sb.AppendLine("    ");
        sb.AppendLine("    if not dfs:");
        sb.AppendLine("        return pd.DataFrame()");
        sb.AppendLine("    ");
        sb.AppendLine("    return pd.concat(dfs, ignore_index=True)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_symbols() -> List[str]:");
        sb.AppendLine("    \"\"\"Get list of symbols in the package.\"\"\"");
        sb.AppendLine("    return load_manifest().get('symbols', [])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_event_types() -> List[str]:");
        sb.AppendLine("    \"\"\"Get list of event types in the package.\"\"\"");
        sb.AppendLine("    return load_manifest().get('eventTypes', [])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    # Example usage");
        sb.AppendLine("    print(f'Symbols: {get_symbols()}')");
        sb.AppendLine("    print(f'Event Types: {get_event_types()}')");
        sb.AppendLine("    ");
        sb.AppendLine("    df = load_data()");
        sb.AppendLine("    print(f'\\nLoaded {len(df):,} records')");
        sb.AppendLine("    print(df.head())");

        return sb.ToString();
    }

    internal static string GenerateRLoader(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Data Loader for " + manifest.Name);
        sb.AppendLine("# Package ID: " + manifest.PackageId);
        sb.AppendLine("# Generated: " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");
        sb.AppendLine();
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("library(dplyr)");
        sb.AppendLine("library(purrr)");
        sb.AppendLine();
        sb.AppendLine("# Get package directory");
        sb.AppendLine("get_package_dir <- function() {");
        sb.AppendLine("  dirname(dirname(rstudioapi::getActiveDocumentContext()$path))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Load manifest");
        sb.AppendLine("load_manifest <- function() {");
        sb.AppendLine("  fromJSON(file.path(get_package_dir(), 'manifest.json'))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Load data with optional filters");
        sb.AppendLine("load_data <- function(symbol = NULL, event_type = NULL, date = NULL) {");
        sb.AppendLine("  manifest <- load_manifest()");
        sb.AppendLine("  package_dir <- get_package_dir()");
        sb.AppendLine("  ");
        sb.AppendLine("  files <- manifest$files");
        sb.AppendLine("  ");
        sb.AppendLine("  # Apply filters");
        sb.AppendLine("  if (!is.null(symbol)) {");
        sb.AppendLine("    files <- files[toupper(files$symbol) == toupper(symbol), ]");
        sb.AppendLine("  }");
        sb.AppendLine("  if (!is.null(event_type)) {");
        sb.AppendLine("    files <- files[tolower(files$eventType) == tolower(event_type), ]");
        sb.AppendLine("  }");
        sb.AppendLine("  ");
        sb.AppendLine("  # Load and combine files");
        sb.AppendLine("  dfs <- map(files$path, function(p) {");
        sb.AppendLine("    full_path <- file.path(package_dir, p)");
        sb.AppendLine("    if (file.exists(full_path)) {");
        sb.AppendLine("      stream_in(file(full_path), verbose = FALSE)");
        sb.AppendLine("    } else {");
        sb.AppendLine("      NULL");
        sb.AppendLine("    }");
        sb.AppendLine("  })");
        sb.AppendLine("  ");
        sb.AppendLine("  bind_rows(compact(dfs))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Get available symbols");
        sb.AppendLine("get_symbols <- function() {");
        sb.AppendLine("  load_manifest()$symbols");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Get available event types");
        sb.AppendLine("get_event_types <- function() {");
        sb.AppendLine("  load_manifest()$eventTypes");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Example usage:");
        sb.AppendLine("# df <- load_data()");
        sb.AppendLine("# df <- load_data(symbol = 'AAPL')");
        sb.AppendLine("# df <- load_data(event_type = 'Trade')");

        return sb.ToString();
    }

    internal static string GenerateImportScript(PackageManifest manifest, ImportScriptTarget target)
    {
        return target switch
        {
            ImportScriptTarget.Python => GeneratePythonImport(manifest),
            ImportScriptTarget.R => GenerateRImport(manifest),
            ImportScriptTarget.PostgreSql => GeneratePostgreSqlImport(manifest),
            ImportScriptTarget.ClickHouse => GenerateClickHouseImport(manifest),
            ImportScriptTarget.Spark => GenerateSparkImport(manifest),
            ImportScriptTarget.DuckDb => GenerateDuckDbImport(manifest),
            _ => $"-- Import script for {target} not yet implemented"
        };
    }

    internal static string GeneratePostgreSqlImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- PostgreSQL Import Script");
        sb.AppendLine($"-- Package: {manifest.Name}");
        sb.AppendLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("-- Create tables");
        sb.AppendLine("CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("    id SERIAL PRIMARY KEY,");
        sb.AppendLine("    timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("    symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("    price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    size BIGINT NOT NULL,");
        sb.AppendLine("    side VARCHAR(10),");
        sb.AppendLine("    exchange VARCHAR(20),");
        sb.AppendLine("    sequence_number BIGINT");
        sb.AppendLine(");");
        sb.AppendLine();
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, timestamp);");
        sb.AppendLine();
        sb.AppendLine("-- Note: For JSONL files, use PostgreSQL's COPY with JSON processing");
        sb.AppendLine("-- or load via Python/psycopg2");

        return sb.ToString();
    }

    internal static string GenerateClickHouseImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- ClickHouse Import Script");
        sb.AppendLine($"-- Package: {manifest.Name}");
        sb.AppendLine();
        sb.AppendLine("CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("    timestamp DateTime64(9),");
        sb.AppendLine("    symbol LowCardinality(String),");
        sb.AppendLine("    price Decimal64(8),");
        sb.AppendLine("    size UInt64,");
        sb.AppendLine("    side LowCardinality(String),");
        sb.AppendLine("    exchange LowCardinality(String)");
        sb.AppendLine(") ENGINE = MergeTree()");
        sb.AppendLine("ORDER BY (symbol, timestamp);");

        return sb.ToString();
    }

    internal static string GenerateDuckDbImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- DuckDB Import Script");
        sb.AppendLine($"-- Package: {manifest.Name}");
        sb.AppendLine($"-- Package ID: {manifest.PackageId}");
        sb.AppendLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("-- Usage: duckdb marketdata.db < import_duckdb.sql");
        sb.AppendLine("-- Or interactively: duckdb marketdata.db");
        sb.AppendLine("--                   .read import_duckdb.sql");
        sb.AppendLine();

        // Trades table with proper schema
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Create trades table with explicit schema");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("    timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("    symbol VARCHAR NOT NULL,");
        sb.AppendLine("    price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    size BIGINT NOT NULL,");
        sb.AppendLine("    side VARCHAR(10),");
        sb.AppendLine("    exchange VARCHAR(20),");
        sb.AppendLine("    sequence_number BIGINT,");
        sb.AppendLine("    stream_id VARCHAR(50)");
        sb.AppendLine(");");
        sb.AppendLine();

        // Quotes table
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Create quotes table");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("CREATE TABLE IF NOT EXISTS quotes (");
        sb.AppendLine("    timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("    symbol VARCHAR NOT NULL,");
        sb.AppendLine("    bid_price DECIMAL(18, 8),");
        sb.AppendLine("    bid_size BIGINT,");
        sb.AppendLine("    ask_price DECIMAL(18, 8),");
        sb.AppendLine("    ask_size BIGINT,");
        sb.AppendLine("    exchange VARCHAR(20)");
        sb.AppendLine(");");
        sb.AppendLine();

        // Bars table
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Create bars (OHLCV) table");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("CREATE TABLE IF NOT EXISTS bars (");
        sb.AppendLine("    timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("    symbol VARCHAR NOT NULL,");
        sb.AppendLine("    open DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    high DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    low DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    close DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("    volume BIGINT NOT NULL,");
        sb.AppendLine("    vwap DECIMAL(18, 8),");
        sb.AppendLine("    trade_count INTEGER");
        sb.AppendLine(");");
        sb.AppendLine();

        // Import instructions for different file formats
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Import data from JSONL files");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Option 1: Auto-detect schema from JSONL");
        sb.AppendLine("-- INSERT INTO trades SELECT * FROM read_json_auto('data/**/trades*.jsonl');");
        sb.AppendLine();
        sb.AppendLine("-- Option 2: Explicit column mapping for trades");
        sb.AppendLine("INSERT INTO trades (timestamp, symbol, price, size, side, exchange, sequence_number, stream_id)");
        sb.AppendLine("SELECT");
        sb.AppendLine("    epoch_ms(CAST(Timestamp AS BIGINT)) AS timestamp,");
        sb.AppendLine("    Symbol AS symbol,");
        sb.AppendLine("    CAST(Price AS DECIMAL(18,8)) AS price,");
        sb.AppendLine("    CAST(Size AS BIGINT) AS size,");
        sb.AppendLine("    Aggressor AS side,");
        sb.AppendLine("    Venue AS exchange,");
        sb.AppendLine("    CAST(SequenceNumber AS BIGINT) AS sequence_number,");
        sb.AppendLine("    StreamId AS stream_id");
        sb.AppendLine("FROM read_json_auto('data/**/trades*.jsonl', ignore_errors=true);");
        sb.AppendLine();

        // Parquet support
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Import from Parquet files (if available)");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- INSERT INTO trades SELECT * FROM read_parquet('data/**/*.parquet');");
        sb.AppendLine();

        // Indexes
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Create indexes for query performance");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(timestamp);");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_quotes_symbol ON quotes(symbol);");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_quotes_timestamp ON quotes(timestamp);");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_bars_symbol ON bars(symbol);");
        sb.AppendLine("CREATE INDEX IF NOT EXISTS idx_bars_timestamp ON bars(timestamp);");
        sb.AppendLine();

        // Summary queries
        sb.AppendLine("-- ============================================");
        sb.AppendLine("-- Verify import with summary queries");
        sb.AppendLine("-- ============================================");
        sb.AppendLine("SELECT 'trades' AS table_name, COUNT(*) AS row_count FROM trades");
        sb.AppendLine("UNION ALL");
        sb.AppendLine("SELECT 'quotes', COUNT(*) FROM quotes");
        sb.AppendLine("UNION ALL");
        sb.AppendLine("SELECT 'bars', COUNT(*) FROM bars;");
        sb.AppendLine();
        sb.AppendLine("-- Show symbols and date ranges");
        sb.AppendLine("SELECT symbol, MIN(timestamp) AS first_trade, MAX(timestamp) AS last_trade, COUNT(*) AS trade_count");
        sb.AppendLine("FROM trades GROUP BY symbol ORDER BY symbol;");

        return sb.ToString();
    }

    internal static string GeneratePythonImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Database Import Script for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("This script imports market data from the package into a PostgreSQL database.");
        sb.AppendLine("Requires: psycopg2, pandas");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("import psycopg2");
        sb.AppendLine("from psycopg2.extras import execute_values");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from typing import Optional");
        sb.AppendLine("import os");
        sb.AppendLine();
        sb.AppendLine("# Database connection settings (override via environment variables)");
        sb.AppendLine("DB_HOST = os.getenv('DB_HOST', 'localhost')");
        sb.AppendLine("DB_PORT = os.getenv('DB_PORT', '5432')");
        sb.AppendLine("DB_NAME = os.getenv('DB_NAME', 'marketdata')");
        sb.AppendLine("DB_USER = os.getenv('DB_USER', 'postgres')");
        sb.AppendLine("DB_PASSWORD = os.getenv('DB_PASSWORD', '')");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_connection():");
        sb.AppendLine("    \"\"\"Create a database connection.\"\"\"");
        sb.AppendLine("    return psycopg2.connect(");
        sb.AppendLine("        host=DB_HOST,");
        sb.AppendLine("        port=DB_PORT,");
        sb.AppendLine("        dbname=DB_NAME,");
        sb.AppendLine("        user=DB_USER,");
        sb.AppendLine("        password=DB_PASSWORD");
        sb.AppendLine("    )");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def create_tables(conn):");
        sb.AppendLine("    \"\"\"Create database tables if they don't exist.\"\"\"");
        sb.AppendLine("    with conn.cursor() as cur:");
        sb.AppendLine("        cur.execute('''");
        sb.AppendLine("            CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("                id SERIAL PRIMARY KEY,");
        sb.AppendLine("                timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("                symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("                price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("                size BIGINT NOT NULL,");
        sb.AppendLine("                side VARCHAR(10),");
        sb.AppendLine("                exchange VARCHAR(20),");
        sb.AppendLine("                sequence_number BIGINT");
        sb.AppendLine("            );");
        sb.AppendLine("            CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, timestamp);");
        sb.AppendLine("            ");
        sb.AppendLine("            CREATE TABLE IF NOT EXISTS quotes (");
        sb.AppendLine("                id SERIAL PRIMARY KEY,");
        sb.AppendLine("                timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("                symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("                bid_price DECIMAL(18, 8),");
        sb.AppendLine("                bid_size BIGINT,");
        sb.AppendLine("                ask_price DECIMAL(18, 8),");
        sb.AppendLine("                ask_size BIGINT");
        sb.AppendLine("            );");
        sb.AppendLine("            CREATE INDEX IF NOT EXISTS idx_quotes_symbol_time ON quotes(symbol, timestamp);");
        sb.AppendLine("        ''')");
        sb.AppendLine("        conn.commit()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def import_trades(conn, df: pd.DataFrame) -> int:");
        sb.AppendLine("    \"\"\"Import trades DataFrame into database.\"\"\"");
        sb.AppendLine("    if df.empty:");
        sb.AppendLine("        return 0");
        sb.AppendLine("    ");
        sb.AppendLine("    columns = ['timestamp', 'symbol', 'price', 'size', 'side', 'exchange', 'sequence_number']");
        sb.AppendLine("    records = []");
        sb.AppendLine("    for _, row in df.iterrows():");
        sb.AppendLine("        records.append((");
        sb.AppendLine("            row.get('Timestamp') or row.get('timestamp'),");
        sb.AppendLine("            row.get('Symbol') or row.get('symbol'),");
        sb.AppendLine("            row.get('Price') or row.get('price'),");
        sb.AppendLine("            row.get('Size') or row.get('size'),");
        sb.AppendLine("            row.get('Side') or row.get('side'),");
        sb.AppendLine("            row.get('Exchange') or row.get('exchange'),");
        sb.AppendLine("            row.get('SequenceNumber') or row.get('sequence_number')");
        sb.AppendLine("        ))");
        sb.AppendLine("    ");
        sb.AppendLine("    with conn.cursor() as cur:");
        sb.AppendLine("        execute_values(cur, '''");
        sb.AppendLine("            INSERT INTO trades (timestamp, symbol, price, size, side, exchange, sequence_number)");
        sb.AppendLine("            VALUES %s");
        sb.AppendLine("        ''', records)");
        sb.AppendLine("        conn.commit()");
        sb.AppendLine("    ");
        sb.AppendLine("    return len(records)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def import_package():");
        sb.AppendLine("    \"\"\"Import all data from the package into the database.\"\"\"");
        sb.AppendLine("    # Load manifest");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        manifest = json.load(f)");
        sb.AppendLine("    ");
        sb.AppendLine("    print(f\"Importing package: {manifest['name']}\")");
        sb.AppendLine("    print(f\"Files: {manifest['totalFiles']}, Events: {manifest['totalEvents']:,}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    conn = get_connection()");
        sb.AppendLine("    create_tables(conn)");
        sb.AppendLine("    ");
        sb.AppendLine("    total_imported = 0");
        sb.AppendLine("    for file_entry in manifest['files']:");
        sb.AppendLine("        file_path = PACKAGE_DIR / file_entry['path']");
        sb.AppendLine("        if not file_path.exists():");
        sb.AppendLine("            continue");
        sb.AppendLine("        ");
        sb.AppendLine("        event_type = file_entry.get('eventType', '').lower()");
        sb.AppendLine("        df = pd.read_json(file_path, lines=True)");
        sb.AppendLine("        ");
        sb.AppendLine("        if event_type == 'trade':");
        sb.AppendLine("            count = import_trades(conn, df)");
        sb.AppendLine("            total_imported += count");
        sb.AppendLine("            print(f\"  Imported {count:,} trades from {file_entry['path']}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    conn.close()");
        sb.AppendLine("    print(f\"\\nTotal records imported: {total_imported:,}\")");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    import_package()");

        return sb.ToString();
    }

    internal static string GenerateRImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Database Import Script for " + manifest.Name);
        sb.AppendLine("# Package ID: " + manifest.PackageId);
        sb.AppendLine("# Generated: " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");
        sb.AppendLine("#");
        sb.AppendLine("# This script imports market data from the package into a PostgreSQL database.");
        sb.AppendLine("# Requires: DBI, RPostgres, jsonlite, dplyr");
        sb.AppendLine();
        sb.AppendLine("library(DBI)");
        sb.AppendLine("library(RPostgres)");
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("library(dplyr)");
        sb.AppendLine();
        sb.AppendLine("# Database connection settings (override via environment variables)");
        sb.AppendLine("DB_HOST <- Sys.getenv('DB_HOST', 'localhost')");
        sb.AppendLine("DB_PORT <- as.integer(Sys.getenv('DB_PORT', '5432'))");
        sb.AppendLine("DB_NAME <- Sys.getenv('DB_NAME', 'marketdata')");
        sb.AppendLine("DB_USER <- Sys.getenv('DB_USER', 'postgres')");
        sb.AppendLine("DB_PASSWORD <- Sys.getenv('DB_PASSWORD', '')");
        sb.AppendLine();
        sb.AppendLine("# Get package directory");
        sb.AppendLine("get_package_dir <- function() {");
        sb.AppendLine("  dirname(dirname(rstudioapi::getActiveDocumentContext()$path))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Create database connection");
        sb.AppendLine("get_connection <- function() {");
        sb.AppendLine("  dbConnect(");
        sb.AppendLine("    Postgres(),");
        sb.AppendLine("    host = DB_HOST,");
        sb.AppendLine("    port = DB_PORT,");
        sb.AppendLine("    dbname = DB_NAME,");
        sb.AppendLine("    user = DB_USER,");
        sb.AppendLine("    password = DB_PASSWORD");
        sb.AppendLine("  )");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Create tables");
        sb.AppendLine("create_tables <- function(conn) {");
        sb.AppendLine("  dbExecute(conn, \"");
        sb.AppendLine("    CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("      id SERIAL PRIMARY KEY,");
        sb.AppendLine("      timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("      symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("      price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("      size BIGINT NOT NULL,");
        sb.AppendLine("      side VARCHAR(10),");
        sb.AppendLine("      exchange VARCHAR(20),");
        sb.AppendLine("      sequence_number BIGINT");
        sb.AppendLine("    );\")");
        sb.AppendLine("  dbExecute(conn, \"CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, timestamp);\")");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Import trades");
        sb.AppendLine("import_trades <- function(conn, df) {");
        sb.AppendLine("  if (nrow(df) == 0) return(0)");
        sb.AppendLine("  ");
        sb.AppendLine("  # Normalize column names");
        sb.AppendLine("  names(df) <- tolower(names(df))");
        sb.AppendLine("  ");
        sb.AppendLine("  # Select and rename columns");
        sb.AppendLine("  trades_df <- df %>%");
        sb.AppendLine("    select(");
        sb.AppendLine("      timestamp = any_of(c('timestamp', 'Timestamp')),");
        sb.AppendLine("      symbol = any_of(c('symbol', 'Symbol')),");
        sb.AppendLine("      price = any_of(c('price', 'Price')),");
        sb.AppendLine("      size = any_of(c('size', 'Size')),");
        sb.AppendLine("      side = any_of(c('side', 'Side')),");
        sb.AppendLine("      exchange = any_of(c('exchange', 'Exchange')),");
        sb.AppendLine("      sequence_number = any_of(c('sequencenumber', 'sequence_number'))");
        sb.AppendLine("    )");
        sb.AppendLine("  ");
        sb.AppendLine("  dbWriteTable(conn, 'trades', trades_df, append = TRUE, row.names = FALSE)");
        sb.AppendLine("  nrow(trades_df)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Main import function");
        sb.AppendLine("import_package <- function() {");
        sb.AppendLine("  package_dir <- get_package_dir()");
        sb.AppendLine("  manifest <- fromJSON(file.path(package_dir, 'manifest.json'))");
        sb.AppendLine("  ");
        sb.AppendLine("  cat(sprintf('Importing package: %s\\n', manifest$name))");
        sb.AppendLine("  cat(sprintf('Files: %d, Events: %s\\n', manifest$totalFiles, format(manifest$totalEvents, big.mark = ',')))");
        sb.AppendLine("  ");
        sb.AppendLine("  conn <- get_connection()");
        sb.AppendLine("  create_tables(conn)");
        sb.AppendLine("  ");
        sb.AppendLine("  total_imported <- 0");
        sb.AppendLine("  for (i in seq_len(nrow(manifest$files))) {");
        sb.AppendLine("    file_entry <- manifest$files[i, ]");
        sb.AppendLine("    file_path <- file.path(package_dir, file_entry$path)");
        sb.AppendLine("    ");
        sb.AppendLine("    if (!file.exists(file_path)) next");
        sb.AppendLine("    ");
        sb.AppendLine("    event_type <- tolower(file_entry$eventType)");
        sb.AppendLine("    df <- stream_in(file(file_path), verbose = FALSE)");
        sb.AppendLine("    ");
        sb.AppendLine("    if (event_type == 'trade') {");
        sb.AppendLine("      count <- import_trades(conn, df)");
        sb.AppendLine("      total_imported <- total_imported + count");
        sb.AppendLine("      cat(sprintf('  Imported %s trades from %s\\n', format(count, big.mark = ','), file_entry$path))");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("  ");
        sb.AppendLine("  dbDisconnect(conn)");
        sb.AppendLine("  cat(sprintf('\\nTotal records imported: %s\\n', format(total_imported, big.mark = ',')))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Run import");
        sb.AppendLine("import_package()");

        return sb.ToString();
    }

    internal static string GenerateSparkImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Apache Spark Import Script for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("This script loads market data from the package into Spark DataFrames.");
        sb.AppendLine("Requires: pyspark");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from pyspark.sql import SparkSession");
        sb.AppendLine("from pyspark.sql.types import (");
        sb.AppendLine("    StructType, StructField, StringType, DecimalType, LongType, TimestampType");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine("# Schema definitions");
        sb.AppendLine("TRADE_SCHEMA = StructType([");
        sb.AppendLine("    StructField('Timestamp', TimestampType(), False),");
        sb.AppendLine("    StructField('Symbol', StringType(), False),");
        sb.AppendLine("    StructField('Price', DecimalType(18, 8), False),");
        sb.AppendLine("    StructField('Size', LongType(), False),");
        sb.AppendLine("    StructField('Side', StringType(), True),");
        sb.AppendLine("    StructField('Exchange', StringType(), True),");
        sb.AppendLine("    StructField('SequenceNumber', LongType(), True)");
        sb.AppendLine("])");
        sb.AppendLine();
        sb.AppendLine("QUOTE_SCHEMA = StructType([");
        sb.AppendLine("    StructField('Timestamp', TimestampType(), False),");
        sb.AppendLine("    StructField('Symbol', StringType(), False),");
        sb.AppendLine("    StructField('BidPrice', DecimalType(18, 8), True),");
        sb.AppendLine("    StructField('BidSize', LongType(), True),");
        sb.AppendLine("    StructField('AskPrice', DecimalType(18, 8), True),");
        sb.AppendLine("    StructField('AskSize', LongType(), True)");
        sb.AppendLine("])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def create_spark_session(app_name: str = 'MarketDataImport') -> SparkSession:");
        sb.AppendLine("    \"\"\"Create a Spark session.\"\"\"");
        sb.AppendLine("    return SparkSession.builder \\");
        sb.AppendLine("        .appName(app_name) \\");
        sb.AppendLine("        .config('spark.sql.session.timeZone', 'UTC') \\");
        sb.AppendLine("        .getOrCreate()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_manifest():");
        sb.AppendLine("    \"\"\"Load the package manifest.\"\"\"");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        return json.load(f)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_trades(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all trade data into a Spark DataFrame.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    trade_files = [");
        sb.AppendLine("        str(PACKAGE_DIR / f['path'])");
        sb.AppendLine("        for f in manifest['files']");
        sb.AppendLine("        if f.get('eventType', '').lower() == 'trade'");
        sb.AppendLine("    ]");
        sb.AppendLine("    ");
        sb.AppendLine("    if not trade_files:");
        sb.AppendLine("        return spark.createDataFrame([], TRADE_SCHEMA)");
        sb.AppendLine("    ");
        sb.AppendLine("    return spark.read.json(trade_files, schema=TRADE_SCHEMA)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_quotes(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all quote data into a Spark DataFrame.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    quote_files = [");
        sb.AppendLine("        str(PACKAGE_DIR / f['path'])");
        sb.AppendLine("        for f in manifest['files']");
        sb.AppendLine("        if f.get('eventType', '').lower() in ('bboquote', 'quote')");
        sb.AppendLine("    ]");
        sb.AppendLine("    ");
        sb.AppendLine("    if not quote_files:");
        sb.AppendLine("        return spark.createDataFrame([], QUOTE_SCHEMA)");
        sb.AppendLine("    ");
        sb.AppendLine("    return spark.read.json(quote_files, schema=QUOTE_SCHEMA)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_all_data(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all data from the package (infers schema).\"\"\"");
        sb.AppendLine("    return spark.read.json(str(DATA_DIR / '**' / '*.jsonl'))");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def save_to_parquet(df, output_path: str, partition_by: list = None):");
        sb.AppendLine("    \"\"\"Save DataFrame to Parquet format.\"\"\"");
        sb.AppendLine("    writer = df.write.mode('overwrite')");
        sb.AppendLine("    if partition_by:");
        sb.AppendLine("        writer = writer.partitionBy(*partition_by)");
        sb.AppendLine("    writer.parquet(output_path)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def main():");
        sb.AppendLine("    \"\"\"Main entry point.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    print(f\"Loading package: {manifest['name']}\")");
        sb.AppendLine("    print(f\"Files: {manifest['totalFiles']}, Events: {manifest['totalEvents']:,}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    spark = create_spark_session()");
        sb.AppendLine("    ");
        sb.AppendLine("    # Load trades");
        sb.AppendLine("    trades_df = load_trades(spark)");
        sb.AppendLine("    print(f\"\\nLoaded {trades_df.count():,} trades\")");
        sb.AppendLine("    trades_df.printSchema()");
        sb.AppendLine("    trades_df.show(5)");
        sb.AppendLine("    ");
        sb.AppendLine("    # Load quotes");
        sb.AppendLine("    quotes_df = load_quotes(spark)");
        sb.AppendLine("    print(f\"\\nLoaded {quotes_df.count():,} quotes\")");
        sb.AppendLine("    quotes_df.printSchema()");
        sb.AppendLine("    quotes_df.show(5)");
        sb.AppendLine("    ");
        sb.AppendLine("    # Example: Save to Parquet with partitioning");
        sb.AppendLine("    # save_to_parquet(trades_df, 'output/trades.parquet', ['Symbol'])");
        sb.AppendLine("    ");
        sb.AppendLine("    spark.stop()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    main()");

        return sb.ToString();
    }
}
